name: Docs • Build & Deploy (caller)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: simutrador/.github/.github/workflows/reusable-mkdocs-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      python_version: "3.12"
      publish_dir: "site"
      # repo:path_in_repo:dest_subdir  (CSV, no spaces after commas)
      aggregate_docs: >-
        simutrador-data-manager:README.md:data-manager,
        simutrador-data-manager:docs:data-manager/docs
    secrets:
      # For private repos, replace with an org secret PAT with repo:read (e.g., ORG_READ_TOKEN)
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
