name: Docs • Build & Deploy (caller)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: simutrador/.github/.github/workflows/reusable-mkdocs-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      python_version: "3.12"
      publish_dir: "site"
      # Pull exactly ONE repo for now: repo : path_in_repo : dest_subdir
      aggregate_docs: >
        simutrador-data-manager:README.md:data-manager,simutrador-data-manager:docs:data-manager/docs,simutrador-data-manager:frontend/README.md:data-manager/frontend,simutrador-data-manager:backend/README.md:data-manager/backend

    secrets:
      # If simutrador-data-manager is private and default token can't read it,
      # create an org secret ORG_READ_TOKEN (classic PAT with repo read) and use it here:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
